In [1]:
import pandas as pd 
import numpy as np 
import plotly.express as px

In [2]:
df=pd.read_csv("creditcard.csv")

In [3]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
df.shape

(284807, 31)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [6]:
df.describe().round(3).T

,count,mean,std,min,25%,50%,75%,max
Time,284807.0,94813.860,47488.146,0.000,54201.500,84692.000,139320.500,172792.000
V1,284807.0,0.000,1.959,-56.408,-0.920,0.018,1.316,2.455
V2,284807.0,0.000,1.651,-72.716,-0.599,0.065,0.804,22.058
V3,284807.0,-0.000,1.516,-48.326,-0.890,0.180,1.027,9.383
V4,284807.0,0.000,1.416,-5.683,-0.849,-0.020,0.743,16.875
V5,284807.0,0.000,1.380,-113.743,-0.692,-0.054,0.612,34.802
V6,284807.0,0.000,1.332,-26.161,-0.768,-0.274,0.399,73.302
V7,284807.0,-0.000,1.237,-43.557,-0.554,0.040,0.570,120.589
V8,284807.0,0.000,1.194,-73.217,-0.209,0.022,0.327,20.007
V9,284807.0,-0.000,1.099,-13.434,-0.643,-0.051,0.597,15.595
V10,284807.0,0.000,1.089,-24.588,-0.535,-0.093,0.454,23.745
V11,284807.0,0.000,1.021,-4.797,-0.762,-0.033,0.740,12.019
V12,284807.0,-0.000,0.999,-18.684,-0.406,0.140,0.618,7.848
V13,284807.0,0.000,0.995,-5.792,-0.649,-0.014,0.663,7.127
V14,284807.0,0.000,0.959,-19.214,-0.426,0.051,0.493,10.527
V15,284807.0,0.000,0.915,-4.499,-0.583,0.048,0.649,8.878
V16,284807.0,0.000,0.876,-14.130,-0.468,0.066,0.523,17.315
V17,284807.0,-0.000,0.849,-25.163,-0.484,-0.066,0.400,9.254
V18,284807.0,0.000,0.838,-9.499,-0.499,-0.004,0.501,5.041
V19,284807.0,0.000,0.814,-7.214,-0.456,0.004,0.459,5.592
V20,284807.0,0.000,0.771,-54.498,-0.212,-0.062,0.133,39.421
V21,284807.0,0.000,0.735,-34.830,-0.228,-0.029,0.186,27.203
V22,284807.0,-0.000,0.726,-10.933,-0.542,0.007,0.529,10.503
V23,284807.0,0.000,0.624,-44.808,-0.162,-0.011,0.148,22.528
V24,284807.0,0.000,0.606,-2.837,-0.355,0.041,0.440,4.585
V25,284807.0,0.000,0.521,-10.295,-0.317,0.017,0.351,7.520
V26,284807.0,0.000,0.482,-2.605,-0.327,-0.052,0.241,3.517
V27,284807.0,-0.000,0.404,-22.566,-0.071,0.001,0.091,31.612
V28,284807.0,-0.000,0.330,-15.430,-0.053,0.011,0.078,33.848
Amount,284807.0,88.350,250.120,0.000,5.600,22.000,77.165,25691.160
Class,284807.0,0.002,0.042,0.000,0.000,0.000,0.000,1.000

In [7]:
df.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
df.duplicated().sum()

1081

In [9]:
df.drop_duplicates(inplace=True,ignore_index=True)

# Data Preprocessing

In [10]:
x = df.drop('Class', axis= 1)
y = df['Class']

In [11]:
y.value_counts()

Class
0    283253
1       473
Name: count, dtype: int64

In [12]:
y.value_counts().round()/len(df)*100

Class
0    99.83329
1     0.16671
Name: count, dtype: float64

* ### Split Data into Train & Test

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 42, stratify= y)

* Handle numerical columns

In [14]:
scalin_col=x_train.columns
scalin_col

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount'],
      dtype='object')

In [15]:
from sklearn.preprocessing import RobustScaler

rc=RobustScaler()

x_train[scalin_col]=rc.fit_transform(x_train)
x_test[scalin_col]=rc.fit_transform(x_test)

In [16]:
x_train

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
225399,0.701730,0.995207,-1.275153,-1.216778,-1.606746,0.801946,3.294124,-1.624678,1.568787,-0.977940,...,-0.758170,-0.291170,-0.053017,0.933343,0.809661,-0.351619,-0.189652,0.224922,-0.467258,0.137472
133746,-0.048166,-0.597600,1.117315,0.218671,-0.010285,-0.269912,-0.591514,0.152452,1.335234,-0.981107,...,-0.015741,-0.506390,-0.891313,1.079738,0.596931,-1.090113,-0.379079,-0.119150,0.301412,-0.209119
185792,0.496931,0.847242,-0.030402,-1.183621,0.095123,0.930577,0.755626,-0.056210,0.295944,0.271802,...,-0.429777,0.776639,1.016689,-0.107803,-2.177118,0.134448,0.104937,0.269659,-0.491127,-0.098808
148925,0.076666,0.803526,0.180212,0.072305,2.453198,0.077371,1.111431,-0.689878,0.395842,0.592835,...,-0.480654,0.403806,0.647327,0.597222,0.832635,-0.341895,0.073567,-0.118813,-0.376486,-0.066242
18398,-0.649581,0.600755,-0.844746,0.194263,-0.959130,-0.875789,0.472816,-1.105189,0.356968,-1.648326,...,-0.867918,-0.752328,-0.601434,0.850633,-0.484676,-0.120272,-0.684600,0.376867,0.012462,0.026608
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224284,0.696608,-0.052287,-0.318477,0.012753,-0.446542,0.298058,0.018909,0.708924,-0.795437,-1.107516,...,0.263579,0.442167,0.935875,0.043539,-0.634005,-0.655851,0.109948,0.244498,-0.121467,1.412417
3493,-0.961003,-0.774125,-0.969796,0.926957,-1.417659,-0.351022,0.587176,0.256491,0.852084,0.896986,...,1.795085,1.194031,0.797266,1.200217,-0.384756,0.608935,0.207174,-0.172246,0.503144,3.322062
241772,0.784493,-0.400567,0.781620,0.206643,0.754956,-0.117891,0.460104,0.293749,0.788802,0.033284,...,-0.845315,-0.173165,-0.154267,0.196908,-0.069535,-0.792390,-1.271150,-1.509753,0.634951,0.206763
60347,-0.416118,0.550658,0.203057,0.214705,0.631807,-0.129952,-0.151581,-0.047286,-0.304063,0.084766,...,0.056196,-0.440363,-0.526329,0.156189,-0.219455,0.579250,-0.960145,0.261919,0.156368,-0.236696
66795,-0.381450,0.450996,-0.204920,0.179462,0.440804,0.152768,1.488727,-0.465729,0.901939,0.534913,...,-0.526037,0.105039,0.393420,0.207819,-1.172318,0.328241,1.041573,0.342908,-0.097591,-0.135394

# Machine Learning

* Logistic Regression

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report


lr=LogisticRegression(random_state= 42, n_jobs= -1,class_weight= 'balanced')
lr.fit(x_train,y_train)

print('\nTrain LR :\n', classification_report(y_train, lr.predict(x_train), target_names=['Not Fraud', 'Fraud']))
print('\nTest LR :\n', classification_report(y_test, lr.predict(x_test), target_names=['Not Fraud', 'Fraud']))

Train LR :
               precision    recall  f1-score   support

   Not Fraud       1.00      0.98      0.99    226602
       Fraud       0.06      0.92      0.12       378

    accuracy                           0.98    226980
   macro avg       0.53      0.95      0.55    226980
weighted avg       1.00      0.98      0.99    226980


Test LR :
               precision    recall  f1-score   support

   Not Fraud       1.00      0.97      0.99     56651
       Fraud       0.05      0.87      0.10        95

    accuracy                           0.97     56746
   macro avg       0.53      0.92      0.54     56746
weighted avg       1.00      0.97      0.99     56746

* Descion Tree

In [18]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state= 42,class_weight= 'balanced')

dt.fit(x_train, y_train)

print('\nTrain dt :\n', classification_report(y_train, dt.predict(x_train),target_names=['Not Fraud', 'Fraud']))
print('\nTest dt :\n', classification_report(y_test, dt.predict(x_test),target_names=['Not Fraud', 'Fraud']))

Train dt :
               precision    recall  f1-score   support

   Not Fraud       1.00      1.00      1.00    226602
       Fraud       1.00      1.00      1.00       378

    accuracy                           1.00    226980
   macro avg       1.00      1.00      1.00    226980
weighted avg       1.00      1.00      1.00    226980


Test dt :
               precision    recall  f1-score   support

   Not Fraud       1.00      1.00      1.00     56651
       Fraud       0.75      0.64      0.69        95

    accuracy                           1.00     56746
   macro avg       0.88      0.82      0.85     56746
weighted avg       1.00      1.00      1.00     56746

* Random Forest

In [19]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state= 42, n_jobs= -1,class_weight= 'balanced')

rf.fit(x_train, y_train)

print('\nTrain rf :\n', classification_report(y_train, rf.predict(x_train),target_names=['Not Fraud', 'Fraud']))
print('\nTest rf :\n', classification_report(y_test, rf.predict(x_test),target_names=['Not Fraud', 'Fraud']))

Train rf :
               precision    recall  f1-score   support

   Not Fraud       1.00      1.00      1.00    226602
       Fraud       1.00      1.00      1.00       378

    accuracy                           1.00    226980
   macro avg       1.00      1.00      1.00    226980
weighted avg       1.00      1.00      1.00    226980


Test rf :
               precision    recall  f1-score   support

   Not Fraud       1.00      1.00      1.00     56651
       Fraud       0.97      0.71      0.82        95

    accuracy                           1.00     56746
   macro avg       0.99      0.85      0.91     56746
weighted avg       1.00      1.00      1.00     56746

* xgbboost

In [ ]:
from xgboost import XGBClassifier


xgb = XGBClassifier(random_state = 42,n_jobs=-1,class_weight= 'balanced')

xgb.fit(x_train, y_train)

print('\nTrain xgb :\n', classification_report(y_train, xgb.predict(x_train)))
print('\nTest xgb :\n', classification_report(y_test, xgb.predict(x_test)))

c:\Users\Sigma\anaconda3\Lib\site-packages\xgboost\training.py:183: UserWarning: [13:41:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "class_weight" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Train xgb :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    226602
           1       0.99      0.98      0.99       378

    accuracy                           1.00    226980
   macro avg       1.00      0.99      0.99    226980
weighted avg       1.00      1.00      1.00    226980


Test xgb :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.78      0.73      0.75        95

    accuracy                           1.00     56746
   macro avg       0.89      0.86      0.88     56746
weighted avg       1.00      1.00      1.00     56746

: